version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: "db-container"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AFEC62CDD545955405CC3BCBD00CE85D
      POSTGRES_DB: rentydb
      PGDATA: /data/postgres
    volumes:
      - postgres_renty:/var/lib/postgresql/data
  api:
    build: ./backend/api/graph
    container_name: "api-container"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      PORT: 8080
      STAGE: dev
      RELEASE: compose
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: AFEC62CDD545955405CC3BCBD00CE85D
      POSTGRES_DB: rentydb
  front:
    image: node:lts-alpine
    container_name: "front-container"
    build: ./frontend
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    expose:
      - "8081"
volumes:
  postgres_renty: ~
