# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "compute_global_address_self_link" {}
variable "compute_instance_group_named_port_name" {}
variable "compute_instance_group_named_port_port" {}
variable "compute_instance_group_self_link" {}
variable "compute_ssl_certificate_self_link" {}
