version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  auth:
    lang: golang-middleware
    handler: ./handler
    image: registry.gitlab.com/ddng/draftlabs/kubebeber/auth:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - gitlab-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
     - jwt-public-key
     - jwt-private-key

