apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-bucket
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'bucket.192-168-1-34.sslip.io'
    routes:
      - matchers:
         - prefix: /minio
        routeAction:
          single:
            upstream:
              name: default-minio-9000
              namespace: gloo-system
        options:
          autoHostRewrite: true