# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "therentyapp-tfstates"
    prefix = "compute-global-address/lb-monitoring-therentyapp-com/terraform.tfstate"
  }
}
