apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      serviceAccountName: default
      containers:
      - image: repo.treescale.com/dave-lopeur/kubebeber/api
        imagePullPolicy: Always
        name: api
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        env:
        - name: DEBUG
          value: "true"
        - name: CONTEXT
          value: kube
        - name: BASE_PATH
          value: "/api"
        - name: gateway-scheme
          value: "http"
        - name: gateway-host
          value: "gateway.openfaas.svc.cluster.local"
        - name: gateway-port
          value: "8080"
        ports:
        - containerPort: 3000
        resources: {}
      imagePullSecrets:
      - name: treescale-registry
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-api
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'api.192-168-1-34.sslip.io'
    options:
      cors:
        allowCredentials: true
        allowHeaders:
        - origin
        - host
        - authorization
        - user-agent
        - content-type
        - accept
        allowMethods:
        - GET
        - POST
        - OPTION
        # allowOrigin:
        # # The scheme portion of the URL is required
        # - 'http://app.192-168-1-34.sslip.io'
        # - '*'
        allowOriginRegex:
        - 'http://[a-zA-Z0-9]*.sslip.io'
        exposeHeaders:
        - origin
        maxAge: 1d
    routes:
      - matchers:
         - prefix: /api
        routeAction:
          single:
            upstream:
              name: default-api-8080
              namespace: gloo-system
        options:
          autoHostRewrite: true
