version: '3'
services:
  front:
    image: node:lts-alpine
    container_name: 'front-container'
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    expose: 
      - '8081'
