version: '3'
services:
  front:
    image: node:lts-alpine
    container_name: 'front-container'
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    expose: 
      - '8080'
