version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  auth:
    lang: golang-middleware
    handler: ./auth
    image: repo.treescale.com/dave-lopeur/kubebeber/auth:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
     - jwt-public-key
     - jwt-private-key
  createuser:
    lang: golang-middleware
    handler: ./createuser
    image: repo.treescale.com/dave-lopeur/kubebeber/createuser:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getofferorbyid:
    lang: golang-middleware
    handler: ./getofferorbyid
    image: repo.treescale.com/dave-lopeur/kubebeber/getofferorbyid:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getofferors:
    lang: golang-middleware
    handler: ./getofferors
    image: repo.treescale.com/dave-lopeur/kubebeber/getofferors:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getrentofferbyid:
    lang: golang-middleware
    handler: ./getrentofferbyid
    image: repo.treescale.com/dave-lopeur/kubebeber/getrentofferbyid:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getrentoffers:
    lang: golang-middleware
    handler: ./getrentoffers
    image: repo.treescale.com/dave-lopeur/kubebeber/getrentoffers:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getuserbyid:
    lang: golang-middleware
    handler: ./getuserbyid
    image: repo.treescale.com/dave-lopeur/kubebeber/getuserbyid:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  getusers:
    lang: golang-middleware
    handler: ./getusers
    image: repo.treescale.com/dave-lopeur/kubebeber/getusers:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
  login:
    lang: golang-middleware
    handler: ./login
    image: repo.treescale.com/dave-lopeur/kubebeber/login:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-dbname
     - arango-tlsverify
     - jwt-private-key
     - jwt-issuer
     - jwt-audience
     - jwt-key-id
     - jwt-expiracy
  sendemail:
    lang: golang-middleware
    handler: ./sendemail
    image: repo.treescale.com/dave-lopeur/kubebeber/sendemail:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-tlsverify
     - arango-assetdbname
     - smtp-host
     - smtp-port
     - smtp-user
     - smtp-password
     - smtp-domain
  getaveragemonthlyrentpersquaremeter:
    lang: golang-middleware
    handler: ./getaveragemonthlyrentpersquaremeter
    image: repo.treescale.com/dave-lopeur/kubebeber/getaveragemonthlyrentpersquaremeter:latest
    environment:
      STAGE:   "dev"
      DEBUG: "true"
      CONTEXT: "openfaas"
    build_args:
      GO111MODULE: on
    secrets:
     - treescale-registry
     - arango-host
     - arango-port
     - arango-scheme
     - arango-user
     - arango-password
     - arango-tlsverify
     - arango-dbname
