// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/BillotP/gorenty/v2/models"
)

// AuthPayload is return by login mutation to get sucess token or error if any
type AuthPayload struct {
	User  *models.User `json:"user"`
	Token *string      `json:"token"`
	Error *string      `json:"error"`
}

// AuthQuery is the payload to authenticate on renty services
type AuthQuery struct {
	Pseudo   string `json:"pseudo"`
	Password string `json:"password"`
}

// EmailInput is used to register a new or updated email including "send me some shit" consentment
type EmailInput struct {
	Value       string `json:"value"`
	InfoConsent bool   `json:"infoConsent"`
}

// FileInput is a file input to request a signed upload url
type FileInput struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
}

// PhoneInput is used to register a new or updated phone number
type PhoneInput struct {
	CountryCode string `json:"countryCode"`
	Value       string `json:"value"`
}

// SearchQuery is a basic search / paging query
type SearchQuery struct {
	Offset *int64  `json:"offset"`
	Count  *int64  `json:"count"`
	Intext *string `json:"intext"`
}

// UserInput is used to register a new or updated user
type UserInput struct {
	Pseudo    string      `json:"pseudo"`
	Gender    string      `json:"gender"`
	FirstName string      `json:"firstName"`
	LastName  string      `json:"lastName"`
	Password  string      `json:"password"`
	Email     *EmailInput `json:"email"`
	Phone     *PhoneInput `json:"phone"`
}
