apiVersion: v1
kind: Service
metadata:
  labels:
    app: renty-web
  name: renty-web
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: renty-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: renty-web
  name: renty-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renty-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: renty-web
    spec:
      containers:
      - image: repo.treescale.com/dave-lopeur/kubebeber/renty-web
        imagePullPolicy: Always
        name: renty-web
        ports:
        - containerPort: 3000
        resources: {}
      imagePullSecrets:
      - name: treescale-registry
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-app
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'app.192-168-1-34.sslip.io'
    routes:
      - matchers:
         - prefix: /
        routeAction:
          single:
            upstream:
              name: default-renty-web-3000
              namespace: gloo-system
        options:
          autoHostRewrite: true
